name: PCPT

channels:
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - python >=3.12.0, <4.0.0
  - pip >=25.2, <26.0
  - numpy >=2.3.0, <3.0.0
  - scipy >=1.16.0, <2.0.0
  - scikit-learn >=1.7.0, <2.0.0
  - matplotlib >=3.10.0, <4.0.0
  - jupyter >=1.1.0, <2.0.0
  - pytorch::pytorch >=2.5.0, <3.0.0
  - pytorch::torchvision >=0.20.0, <1.0.0
  - pytorch::torchaudio >=2.5.0, <3.0.0
  - pip:
    - nbconvert[webpdf] >=7.16.0, <8.0.0
    - nbstripout >=0.8.0, <1.0.0
    - torchinfo >=1.8.0, <2.0.0
